services:
  # Your ASP.NET Core Web API
  api:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - AppSettings__Token=${JWT_SECRET}
    depends_on:
      - postgres-db
      - mongo-db
    command: dotnet watch run --project WebAPI/WebAPI.csproj --urls "http://+:8080"

  # PostgreSQL Database for relational data (Users, Groups)
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=chatdb

  # MongoDB for unstructured data (Messages)
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  postgres_data:
  mongo_data:
